apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-app
  template:
    metadata:
      labels:
        app: car-app
    spec:
      containers:
      - name: car-app
        image: 228096284456.dkr.ecr.ap-south-2.amazonaws.com/cargame:final
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  type: LoadBalancer
  selector:
    app: car-app
  ports:
    - port: 80
      targetPort: 5000
